#@ load("@ytt:data", "data")

---
name: #@ data.values.cluster_name
description: #@ data.values.cluster_description
clusterType: WORKLOAD
clusterTemplateName: #@ data.values.cluster_template_name
hcxCloudUrl: #@ data.values.hcx_cloud_url
vmTemplate: photon-3-kube-v1.18.6+vmware.1
lbTemplate: photon-3-haproxy-v1.2.4+vmware.1
placementParams:
- type: Network
  name: VL1250
- type: Folder
  name: K8
- type: Datastore
  name: ndc-ds-vsan01
- type: ResourcePool
  name: Dish-k8s
- type: ClusterComputeResource
  name: ndc-cl01
clusterConfig:
  csi:
    - name: nfs_client
      properties:
        serverIP: 10.252.252.241
        mountPath: /default-share
  tools:
    - name: harbor
      properties:
        type: extension
        extensionId: c185b4c6-7f6e-4865-a6bd-ac0bbf2074ba
managementClusterName: ncd-k8s-mgmt-cl01
masterNodes:
  - name: ndc-workload-mc1
    networks:
    - label: k8s-mgmt-network
      networkName: management
workerNodes:
  - name: ndc-workload-1
    networks:
      - label: k8s-mgmt-network
        networkName: VL1250
      - label: oam-network
        networkName: VL1250
      - label: signalling-network
        networkName: VL1250
      - label: n35
        networkName: VL1250
